homing_controller:
  type: reemc_controllers/ReemcHomingController 
  joints:
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_4_joint
    - leg_right_5_joint
    - leg_right_6_joint
    - torso_1_joint
    - torso_2_joint
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
    - head_1_joint
    - head_2_joint
  actuators:
    - leg_left_1_motor
    - leg_left_2_motor
    - leg_left_3_motor
    - leg_left_4_motor
    - leg_left_5_motor
    - leg_left_6_motor
    - leg_right_1_motor
    - leg_right_2_motor
    - leg_right_3_motor
    - leg_right_4_motor
    - leg_right_5_motor
    - leg_right_6_motor
    - torso_1_motor
    - torso_2_motor
    - arm_left_1_motor
    - arm_left_2_motor
    - arm_left_3_motor
    - arm_left_4_motor
    - arm_left_5_motor
    - arm_left_6_motor
    - arm_left_7_motor
    - arm_right_1_motor
    - arm_right_2_motor
    - arm_right_3_motor
    - arm_right_4_motor
    - arm_right_5_motor
    - arm_right_6_motor
    - arm_right_7_motor
