actuators:
  raw_data:

    position_port: act_position
    effort_port: act_current
    mode_port: act_control_mode
    position_cmd_port: ref_position
    effort_cmd_port: ref_current
    mode_cmd_port: ref_control_mode
    current_limit_cmd_port: ref_limit_current

e_stop:
  raw_data:
    e_stop_port: emergency_stop_state

force_torque:
  left_ankle_ft:
    frame: left_sole_link
    raw_data:
      force_port: force_ankle_left
      torque_port: torque_ankle_left
  right_ankle_ft:
    frame: right_sole_link
    raw_data:
      force_port: force_ankle_right
      torque_port: torque_ankle_right
  left_wrist_ft:
    frame: wrist_left_ft_link
    transformation:
      force: [y,-x,-z]
      torque: [y,-x,-z]
    raw_data:
      force_port: force_wrist_left
      torque_port: torque_wrist_left
  right_wrist_ft:
    frame: wrist_right_ft_link
    transformation:
      force: [-y,x,-z]
      torque: [-y,x,-z]
    raw_data:
      force_port: force_wrist_right
      torque_port: torque_wrist_right

imu:
  base_imu:
    frame: base_link
    raw_data:
      orientation_port: orientation_base
      linear_acceleration_port: linear_acceleration_base
      angular_velocity_port: angular_velocity_base

ros_control_component:
  ignore_read_errors: false
