actuators:
  raw_data:
    position_port: act_position
    effort_port: act_current
    position_cmd_port: ref_position
    current_limit_cmd_port: ref_limit_current

e_stop:
  raw_data:
    e_stop_port: emergency_stop_state

force_torque:
  left_ft:
    frame: leg_left_6_link
    raw_data:
      force_port: force_left
      torque_port: torque_left
  right_ft:
    frame: leg_right_6_link
    raw_data:
      force_port: force_right
      torque_port: torque_right

imu:
  base_imu:
    frame: base_link
    raw_data:
      orientation_port: orientation_base

ros_control_component:
  ignore_read_errors: false
